/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mntgeneration.forms;

import com.mntgeneration.utils.FieldListFiller;
import com.mntgeneration.utils.FormUtils;
import com.mntgeneration.utils.TypeOfGenerationEnum;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jose.alvarez.villar
 */
public class MainForm extends javax.swing.JFrame {

    private TypeOfGenerationEnum typeOfGenerationSelected;
    private DefaultListModel<String> fieldListModel;

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        FormUtils.centreWindow(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partyOptionGroup = new javax.swing.ButtonGroup();
        selectPartyTypeLabel = new javax.swing.JLabel();
        customerRadioButton = new javax.swing.JRadioButton();
        employeeRadioButton = new javax.swing.JRadioButton();
        custEmplRadioButton = new javax.swing.JRadioButton();
        nextMainButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Party Generator");
        setPreferredSize(new java.awt.Dimension(708, 516));

        selectPartyTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectPartyTypeLabel.setText("Please select the type of the file you want to generate:");

        partyOptionGroup.add(customerRadioButton);
        customerRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        customerRadioButton.setText("I want to generate a customer MNT file");
        customerRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customerRadioButtonItemStateChanged(evt);
            }
        });

        partyOptionGroup.add(employeeRadioButton);
        employeeRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employeeRadioButton.setText("I want to generate an employee MNT file");
        employeeRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                employeeRadioButtonItemStateChanged(evt);
            }
        });

        partyOptionGroup.add(custEmplRadioButton);
        custEmplRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        custEmplRadioButton.setText("I want to generate a customer + employee in a single MNT file");
        custEmplRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                custEmplRadioButtonItemStateChanged(evt);
            }
        });

        nextMainButton.setText("Next");
        nextMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(selectPartyTypeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custEmplRadioButton)
                                    .addComponent(employeeRadioButton)
                                    .addComponent(customerRadioButton))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nextMainButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(selectPartyTypeLabel)
                .addGap(18, 18, 18)
                .addComponent(customerRadioButton)
                .addGap(18, 18, 18)
                .addComponent(employeeRadioButton)
                .addGap(18, 18, 18)
                .addComponent(custEmplRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(nextMainButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextMainButtonActionPerformed
        if( partyOptionGroup.getSelection() == null) { //.getSelectedObjects().length == 0
            JOptionPane.showMessageDialog(this, "Please select the type of file you would like to produce", "Don't be lazy", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (this.getTypeOfGenerationSelected() != TypeOfGenerationEnum.CUSTOMER_EMPLOYEE ) {
            this.fieldListModel = FieldListFiller.getFields(this.getTypeOfGenerationSelected().getPath());
        } else {
            this.fieldListModel = FieldListFiller.getFields(TypeOfGenerationEnum.CUSTOMER.getPath());
            DefaultListModel<String> employeeFieldList = FieldListFiller.getFields(TypeOfGenerationEnum.EMPLOYEE.getPath());
            for (int  i = 0 ; i < employeeFieldList.getSize(); i++ ) {
                if (!this.fieldListModel.contains(employeeFieldList.getElementAt(i))) {
                    this.fieldListModel.addElement(employeeFieldList.getElementAt(i));
                }
            }
        }
        ShowFieldsListForm showFieldsListForm = new ShowFieldsListForm(this);
        showFieldsListForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nextMainButtonActionPerformed

    private void customerRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customerRadioButtonItemStateChanged
        this.typeOfGenerationSelected = TypeOfGenerationEnum.CUSTOMER;
    }//GEN-LAST:event_customerRadioButtonItemStateChanged

    private void employeeRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_employeeRadioButtonItemStateChanged
        this.typeOfGenerationSelected = TypeOfGenerationEnum.EMPLOYEE;
    }//GEN-LAST:event_employeeRadioButtonItemStateChanged

    private void custEmplRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_custEmplRadioButtonItemStateChanged
        this.typeOfGenerationSelected = TypeOfGenerationEnum.CUSTOMER_EMPLOYEE;
    }//GEN-LAST:event_custEmplRadioButtonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    public TypeOfGenerationEnum getTypeOfGenerationSelected() {
        return typeOfGenerationSelected;
    }

    public DefaultListModel<String> getFieldListModel() {
        return this.fieldListModel;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton custEmplRadioButton;
    private javax.swing.JRadioButton customerRadioButton;
    private javax.swing.JRadioButton employeeRadioButton;
    private javax.swing.JButton nextMainButton;
    private javax.swing.ButtonGroup partyOptionGroup;
    private javax.swing.JLabel selectPartyTypeLabel;
    // End of variables declaration//GEN-END:variables

}
